### ISSUE TITLE
Improve DOMMatrix tests

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-test#1068]
See https://github.com/w3c/csswg-test/pull/1066#issuecomment-200282676

cc @peterjoel

**Comment by peterjoel** [comment]
@zcorpan You can assign to me. I'm doing this anyway while implementing.

**Comment by hwanseung** [comment]
hi, i have a question.
present test suite of geometry interfaces is seem like based on Candidate Recommendation(https://www.w3.org/TR/geometry-1/).
is it can not based on Editor’s Draft(https://drafts.fxtf.org/geometry)?
or can we make new folder for Editor's Draft in order to distinguish with Candidate Recommendation.
if Editor's Draft were needed, i want to contribute to update test suite.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5480; please continue all discussion there.
