### ISSUE TITLE
Travis build: Extract tool tarballs instead of cloning hg repos

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-test#861]
Currently, the Travis build [tries to `hg clone` 2 tool repos](https://github.com/w3c/csswg-test/blob/39770a08bd3add1fe14dd2f203c4592cb4bedea4/tools/travis/build.py#L20), which tends to cause [Travis errors or timeouts](https://travis-ci.org/w3c/csswg-test/builds/80201151) due to how long the full clones take and network unreliability. It would be much faster to just download and extract the repos' tarballs (e.g. https://hg.csswg.org/dev/apiclient/archive/tip.tar.gz ) instead.
CC: @Ms2ger

**Comment by Ms2ger** [comment]
Are those cached? I believe those archives are typically generated on the fly. @indygreg probably knows.

**Comment by plinss** [comment]
The tabballs are generated on the fly.

**Comment by jgraham** [comment]
Are you caching the clone on travis?

**Comment by cvrebert** [comment]
The current Travis config doesn't setup any caching.

**Comment by Ms2ger** [comment]
@cvrebert I don't have the time to figure out how travis caching works, but would be happy to work with you if you want to pursue this.

**Comment by indygreg** [comment]
I would rather we not reinvent repository cloning.

`hg clone` with bundleclone enabled and configured to prefer "stream bundles" will be almost as fast as raw tarballs. The server advertises URLs in S3 and CloudFront, so you really shouldn't have a problem with connectivity availability or speed. When buildbot jobs enabled bundleclone, a lot of issues went away.

More info at http://mozilla-version-control-tools.readthedocs.org/en/latest/hgmo/bundleclone.html

I'm getting this feature built into Mercurial itself so little to no client-side configuration is needed. I also have some ideas for performance improvements so `hg clone` is faster than `tar`. Please stick with `hg clone` because it is simpler and will only get faster and better over time.

**Comment by cvrebert** [comment]
But the build doesn't care about the commit history, only the current state of the repos, and FWICT Mercurial doesn't support shallow clones. Seems like not cloning ought to be faster from an information theoretic perspective.

**Comment by indygreg** [comment]
The tools repo is less than 30 MB (https://hg.cdn.mozilla.net/). You aren't talking about a lot of overhead no matter what the solution.

IMO it's worth having the full history around so incremental pulls are fast and so tools can pull data from version control. This may only be relevant on the builders. But just this week we were talking about things like doing away with test archives and having test machines maintain clones.

Mercurial does have shallow clone. We just don't (yet) have it deployed on hg.mozilla.org. There's a bug for it somewhere and it's on my long list of things to experiment with.

Due to the nature of shallow clone and the optimizations in bundleclone it's actually possible to obtain a full clone in less time than a shallow clone. It costs more network and disk, but it's *fast*. e.g. we can do a full Firefox clone in Mercurial faster than a shallow clone in Git, for example. It's also a lot less CPU on the server, which makes the server easier to scale and cheaper to run.

Don't add extra complexity: stick with `hg clone` (+bundleclone until Mercurial 3.6 - assuming it ships in 3.6).

**Comment by cvrebert** [comment]
> The tools repo is less than 30 MB (https://hg.cdn.mozilla.net/).

Perhaps there is some confusion. The tools being referred to are `apiclient` and `w3ctestlib`, not https://hg.mozilla.org/build/tools/
Or are copies of them buried deeper in that directory tree?

> IMO it's worth having the full history around so incremental pulls are fast and so tools can pull data from version control. This may only be relevant on the builders.

The Travis build doesn't seem to use the history of `apiclient` or `w3ctestlib` at all. No idea what the use-case for their history would be. And unless someone sets up Travis' caching feature, the pulls will always be from-scratch, never incremental.

> Mercurial does have shallow clone. We just don't (yet) have it deployed on hg.mozilla.org

Not quite sure why you're mentioning hg.mozilla.org. The clones are from CSSWG's Mercurial server (see https://github.com/w3c/csswg-test/blob/e509cafdb9417b4f0c4c2648020b80e47564c73a/tools/travis/build.py#L19-L20 ), not hg.mozilla.org. Or does Mozilla run CSSWG's Mercurial server or something? I have no knowledge of CSSWG's server infrastructure.

**Comment by plinss** [comment]
csswg.org is owned and operated by me personally, and has no relation or connection to mozilla.org

**Comment by indygreg** [comment]
@Ms2ger referenced me and I figured we were talking about hg.mozilla.org. Never mind me then.

Looking at the initial comment, you should exercise caution before downloading URLs like https://hg.csswg.org/dev/apiclient/archive/tip.tar.gz because the server will generate an archive on the fly for every request. That's a good way to DoS a Mercurial server. For small repos and low traffic consumers, it's probably tolerable. `hg clone --uncompressed` performs a clone with the least impact on server resources. Once my Mercurial static bundle clone work is implemented, then server operators will be able to advertise URLs to pre-generated bundles to reduce server load even further.

**Comment by gsnedders** [comment]
Using Travis CI's caching functionality seems like it would mostly solve this, no?

**Comment by cvrebert** [comment]
That's another viable option, yes.

**Comment by cvrebert** [comment]
Here's a PR that sets up Travis caching: #908
